---
# This playbook prepares a CentOS 7 VM for DC/OS installation via Vagrant

- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - dcos-node
    - debug
    - vagrant
    - guestadditions
    - cleanup
