---
# Cache Docker images for use by the bootstrap machine to speed up install

- name: Install Docker-Py
  pip:
    name: docker-py
    version: 1.9.0

- name: Cache jplock/zookeeper docker image
  docker_image:
    name: jplock/zookeeper:3.5.5
    tag: zookeper
    source: pull

- name: Cache nginx docker image
  docker_image:
    name: nginx:latest
    tag: nginx
    source: pull

- name: Cache registry docker image
  docker_image:
    name: registry:2
    tag: registry
    source: pull
